export default [
  "Agente Inmobiliario",
  "Albañil",
  "Albañil Fino",
  "Armador de Muebles",
  "Atención al Cliente",
  "Auxiliar de Limpieza",
  "Barista",
  "Bartender",
  "Barbero",
  "Bordador",
  "Cajero",
  "Carnicero",
  "Carpintero",
  "Cerrajero",
  "Chapa y Pintura",
  "Chofer",
  "Chofer Profesional",
  "Cocinero",
  "Colocador de Cerámicos",
  "Colocador de Durlock",
  "Community Manager",
  "Cosmetóloga",
  "Costurera",
  "Decorador",
  "Delivery",
  "Detailer Automotor",
  "Diseñador de Indumentaria",
  "Diseñador Gráfico",
  "DJ",
  "Electricista",
  "Entrenador Personal",
  "Estilista",
  "Fletes",
  "Fotógrafo",
  "Fotografía Inmobiliaria",
  "Fresador",
  "Fumigador",
  "Gasista",
  "Guía de Turismo",
  "Guardavidas",
  "Herrero",
  "Herrería Artística",
  "Impresor 3D",
  "Instalador de Aires Acondicionados",
  "Instalador de Alfombras",
  "Instalador de Pisos Vinílicos",
  "Instalador de Redes",
  "Jardinero",
  "Kinesiólogo Deportivo",
  "Lavacoches",
  "Limpieza de Casas",
  "Limpieza de Oficinas",
  "Limpieza Industrial",
  "Limpiavidrios",
  "Maquilladora",
  "Manicura",
  "Masajista",
  "Mecánico",
  "Mecánico de Bicicletas",
  "Mecánico de Motos",
  "Modista",
  "Montador de Muebles",
  "Montajista",
  "Mozo",
  "Mudanzas",
  "Multiservicios",
  "Niñera",
  "Operador de Cámaras",
  "Operador de Drones",
  "Operario Industrial",
  "Panadero",
  "Parquero",
  "Pastelero",
  "Pedicura",
  "Peluquero",
  "Pescadero",
  "Pintor",
  "Pintor Automotor",
  "Plomero",
  "Podador",
  "Profesor Particular",
  "Profesor de Música",
  "Profesor de Guitarra",
  "Profesor de Canto",
  "Programador Freelance",
  "Redactor Freelance",
  "Repositor",
  "Repartidor",
  "Sanitario",
  "Seguridad Privada",
  "Soldador",
  "Soguero",
  "Tapicero",
  "Tapicero Automotor",
  "Techista",
  "Técnico Electrónico",
  "Técnico en Celulares",
  "Técnico en Electrodomésticos",
  "Técnico en Refrigeración",
  "Técnico Informático",
  "Tornero",
  "Traductor",
  "Vidriero",
  "Vigilador",
  "Yesero",
  "Otro"
];
